GET http://localhost:3333 HTTP/1.1

###

GET http://localhost:3333/mensagem HTTP/1.1

###

POST http://localhost:3333/dados HTTP/1.1
content-type: application/json

{
    "nome": "Pedro Euzebio",
    "idade": "18"
}
