POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{
  "nome": "Pedro",
  "email": "pedro@gmail.com",
  "idade": "18"
}

###

PUT http://localhost:3333/users/1 HTTP/1.1
content-type: application/json

{
  "nome": "Pedro Euzebio",
  "email": "pedro.euzebio@gmail.com",
  "idade": "21"
}

###

DELETE http://localhost:3333/users/1 HTTP/1.1
